apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: default
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook
  namespace: default 
spec:
  secretName: webhook-tls
  dnsNames:
    - $(WEBHOOK_NAME).$(NAMESPACE).svc
  issuerRef:
    name: selfsigned
---

apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls
  namespace: default
